### ISSUE TITLE
TypeError: Cannot read property 'displayName' of null

### ISSUE THREAD

**Issue by iCiaran** [HopsonCommunity/HopsonBot#37]
```
TypeError: Cannot read property 'displayName' of null
    at logMessageInfo (/home/hopbot/HopsonBot/src/events/message_sent_handler.js:103:33)
    at MessageSentHandler.handleMessageSent (/home/hopbot/HopsonBot/src/events/message_sent_handler.js:26:9)
    at Client.client.on (/home/hopbot/HopsonBot/src/hopson_bot.js:31:37)
    at Client.emit (events.js:159:13)
    at MessageCreateHandler.handle (/home/hopbot/HopsonBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/hopbot/HopsonBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/hopbot/HopsonBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/hopbot/HopsonBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/hopbot/HopsonBot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:159:13)
```

Can just check if it's null first but would rather know what caused it.

**Comment by Hopson97** [comment]
:thinking:

**Comment by Hopson97** [comment]
Is this still an issue?
